// This file provides mock data for the application when the actual database is not available

// Mock data for students
export const students = [
  {
    id: 1,
    name: "Rahul Sharma",
    email: "rahul.s@srm.edu",
    phone: "9876543210",
    department: "Computer Science",
    year: 3,
    role: "Student",
    address: "123 College Road, Chennai",
  },
  {
    id: 2,
    name: "Priya Patel",
    email: "priya.p@srm.edu",
    phone: "9876543211",
    department: "Electronics",
    year: 2,
    role: "Club President",
    address: "456 University Avenue, Chennai",
  },
  {
    id: 3,
    name: "Amit Kumar",
    email: "amit.k@srm.edu",
    phone: "9876543212",
    department: "Mechanical",
    year: 4,
    role: "Student",
    address: "789 Campus Street, Chennai",
  },
  {
    id: 4,
    name: "Sneha Gupta",
    email: "sneha.g@srm.edu",
    phone: "9876543213",
    department: "Civil Engineering",
    year: 3,
    role: "Club Secretary",
    address: "101 Engineering Block, Chennai",
  },
  {
    id: 5,
    name: "Vikram Singh",
    email: "vikram.s@srm.edu",
    phone: "9876543214",
    department: "Information Technology",
    year: 2,
    role: "Student",
    address: "202 IT Park, Chennai",
  },
]

// Mock data for clubs
export const clubs = [
  {
    id: 1,
    name: "Coding Club",
    domain: "Technical",
    foundedYear: 2018,
    description: "A club for coding enthusiasts to learn and grow together",
    presidentId: 2,
    vicePresidentId: 4,
    email: "coding.club@srm.edu",
  },
  {
    id: 2,
    name: "Robotics Club",
    domain: "Technical",
    foundedYear: 2017,
    description: "Building robots and exploring automation technologies",
    presidentId: 3,
    vicePresidentId: 5,
    email: "robotics.club@srm.edu",
  },
  {
    id: 3,
    name: "Entrepreneurship Club",
    domain: "Business",
    foundedYear: 2019,
    description: "Fostering entrepreneurial skills and startup culture",
    presidentId: 1,
    vicePresidentId: 2,
    email: "e.club@srm.edu",
  },
  {
    id: 4,
    name: "Design Club",
    domain: "Creative",
    foundedYear: 2020,
    description: "Exploring design thinking and creative solutions",
    presidentId: 4,
    vicePresidentId: 1,
    email: "design.club@srm.edu",
  },
  {
    id: 5,
    name: "AI Research Club",
    domain: "Technical",
    foundedYear: 2021,
    description: "Researching and implementing AI solutions",
    presidentId: 5,
    vicePresidentId: 3,
    email: "ai.club@srm.edu",
  },
]

// Mock data for events
export const events = [
  {
    id: 1,
    name: "Tech Symposium",
    description: "Annual technical symposium featuring workshops, competitions, and talks",
    date: "2023-12-15",
    time: "09:00",
    location: "Main Auditorium",
    budget: 50000,
    type: "Technical",
    footfall: 500,
    clubId: 1,
  },
  {
    id: 2,
    name: "Robotics Workshop",
    description: "Hands-on workshop on building and programming robots",
    date: "2023-12-20",
    time: "10:00",
    location: "Engineering Lab",
    budget: 30000,
    type: "Workshop",
    footfall: 100,
    clubId: 2,
  },
  {
    id: 3,
    name: "Startup Pitch Day",
    description: "Platform for students to pitch their startup ideas to investors",
    date: "2024-01-10",
    time: "14:00",
    location: "Business Center",
    budget: 25000,
    type: "Competition",
    footfall: 200,
    clubId: 3,
  },
  {
    id: 4,
    name: "Design Thinking Workshop",
    description: "Workshop on design thinking methodology and its applications",
    date: "2024-01-15",
    time: "11:00",
    location: "Design Studio",
    budget: 20000,
    type: "Workshop",
    footfall: 80,
    clubId: 4,
  },
  {
    id: 5,
    name: "AI Conference",
    description: "Conference on latest advancements in artificial intelligence",
    date: "2024-02-05",
    time: "09:30",
    location: "Research Center",
    budget: 60000,
    type: "Conference",
    footfall: 300,
    clubId: 5,
  },
]

// Mock data for other entities can be added as needed
export const sessions = [
  {
    id: 1,
    name: "Introduction to Python",
    clubId: 1,
    speaker: "Dr. Rajesh Kumar",
    date: "2023-12-10",
    time: "14:00",
    mode: "Offline",
    duration: "02:00:00",
    type: "Workshop",
  },
  {
    id: 2,
    name: "Arduino Basics",
    clubId: 2,
    speaker: "Prof. Meena Sharma",
    date: "2023-12-12",
    time: "10:00",
    mode: "Hybrid",
    duration: "03:00:00",
    type: "Training",
  },
]

export const funds = [
  {
    id: 1,
    clubId: 1,
    source: "University Grant",
    amount: 100000,
    date: "2023-11-01",
    type: "Income",
    balance: 75000,
    status: "Approved",
  },
  {
    id: 2,
    clubId: 2,
    source: "Sponsorship",
    amount: 50000,
    date: "2023-11-15",
    type: "Income",
    balance: 50000,
    status: "Approved",
  },
]

export const expenses = [
  {
    id: 1,
    clubId: 1,
    eventName: "Tech Symposium",
    description: "Venue booking and equipment rental",
    amount: 25000,
    paymentMethod: "Bank Transfer",
    approvedBy: "Dr. Suresh Kumar",
  },
  {
    id: 2,
    clubId: 2,
    eventName: "Robotics Workshop",
    description: "Components and materials",
    amount: 15000,
    paymentMethod: "Cash",
    approvedBy: "Prof. Anita Desai",
  },
]

export const resources = [
  {
    id: 1,
    name: "Projector",
    description: "High-definition projector for presentations",
    quantity: 2,
    availability: "Available",
    cost: 50000,
    maintenanceSchedule: "Quarterly",
    clubId: 1,
  },
  {
    id: 2,
    name: "Laptop",
    description: "High-performance laptop for coding and design work",
    quantity: 5,
    availability: "Available",
    cost: 75000,
    maintenanceSchedule: "Yearly",
    clubId: 1,
  },
]

export const announcements = [
  {
    id: 1,
    clubId: 1,
    title: "Registration for Tech Fest",
    content: "Registration for the annual Tech Fest is now open. Register before December 15th to participate.",
    date: "2023-12-01",
    audience: "All Members",
    expiryDate: "2023-12-15",
    status: "Visible",
  },
  {
    id: 2,
    clubId: 3,
    title: "Entrepreneurship Workshop",
    content: "Join us for a workshop on entrepreneurship basics on December 10th.",
    date: "2023-12-05",
    audience: "Club Members",
    expiryDate: "2023-12-10",
    status: "Visible",
  },
]

export const feedback = [
  {
    id: 1,
    eventId: 1,
    studentId: 3,
    rating: 4,
    comments: "The event was well organized and informative.",
    date: "2023-12-16",
    suggestion: "Could improve the sound system.",
    anonymous: false,
  },
  {
    id: 2,
    eventId: 2,
    studentId: 4,
    rating: 5,
    comments: "Excellent workshop, learned a lot about robotics.",
    date: "2023-12-21",
    suggestion: "More hands-on activities would be great.",
    anonymous: true,
  },
]

export const reports = [
  {
    id: 1,
    clubId: 1,
    year: 2023,
    totalEvents: 12,
    totalFundsUsed: 120000,
    achievements: "Won the Best Technical Club Award",
    challenges: "Limited budget for advanced equipment",
    summary: "Overall a successful year with increased membership and activities",
  },
  {
    id: 2,
    clubId: 2,
    year: 2023,
    totalEvents: 8,
    totalFundsUsed: 90000,
    achievements: "Organized the first inter-college robotics competition",
    challenges: "Difficulty in procuring specialized components",
    summary: "Made significant progress in establishing the club's reputation",
  },
]
